development:
  adapter: mysql
  database: cs_vpc_dev
  username: root
  password:
  host: localhost

test:
  adapter: mysql
  database: cs_vpc_test
  username: root
  password:

production:
  adapter: mysql
  database: cs_vpc_prod
  username: root
  password:
